version: "3"

services:
  org-github-runner:
    image: myoung34/github-runner:latest
    container_name: org-github-runner
    restart: always
    environment:
      ORG_NAME: ${ORG_NAME}
      ACCESS_TOKEN: ${ACCESS_TOKEN}  # Optional for managing via API
      RUNNER_SCOPE: org
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_NAME: ${RUNNER_NAME}
      RUNNER_LABELS: ${RUNNER_LABELS}
      RUNNER_GROUP: Default
      RUNNER_WORKDIR: /tmp/runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
