version: "3" 
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket to allow Watchtower to monitor containers

  adguardhome:
    image: adguard/adguardhome
    volumes:
      - ${ADGUARD_HOME}/work:/opt/adguardhome/work
      - ${ADGUARD_HOME}/conf:/opt/adguardhome/conf
    environment:
      TZ: Africa/Casablanca
    ports:
      - 3000:3000
      - 53:53/udp
      - 53:53/tcp
    networks:
      - host
    restart: unless-stopped

networks:
  host:
    external: true
