version: "3" 
services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    
    restart: always
    environment:
      TZ: "Europe/Paris"
      WUD_WATCHER_LOCAL_CRON: "0 1 * * *" # everyday at 1 am
      WUD_TRIGGER_TELEGRAM_1_BOTTOKEN: ${TELEGRAM_TOKEN}
      WUD_TRIGGER_TELEGRAM_1_CHATID: ${TELEGRAM_CHAT_ID}
      WUD_TRIGGER_DOCKER_localdocker_PRUNE: true


  noip-duc:
    image: noipcom/noip-duc:latest
    container_name: noip-duc
    restart: unless-stopped
    environment:
      NOIP_USERNAME: ${NOIP_USERNAME}
      NOIP_PASSWORD: ${NOIP_PASSWORD}
      NOIP_HOSTNAMES: ${NOIP_HOSTNAMES}
    
  adguardhome:
    image: adguard/adguardhome
    volumes:
      - ${ADGUARD_HOME}/work:/opt/adguardhome/work
      - ${ADGUARD_HOME}/conf:/opt/adguardhome/conf
    environment:
      TZ: Africa/Casablanca
    ports:
      - 3000:3000
      - 53:53/udp
      - 53:53/tcp
    network_mode: host
    restart: unless-stopped
    
