---
version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 801:80/tcp
      - 4431:443/tcp
    volumes:
      - /srv/appdata/adguard/workdir:/opt/adguardhome/work
      - /srv/appdata/adguard/confdir:/opt/adguardhome/conf
    environment:
      TZ: Europe/Brussels
    restart: unless-stopped